version: '3.8'

services:
  web:
    build: .
    ports:
      - "4000:80"
    environment:
      - NAME=Roda
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
